### ISSUE TITLE
Setting the environment for Linux

### ISSUE THREAD

**Issue by lisalenorelowe** [schism-dev/schism_visit_plugin#4]
Hello,

I am trying to compile the plugin for Linux, and my notes are here:
https://github.com/lisalenorelowe/schism_visit_plugin/blob/master/linux_build_instructions.md

When 'make'-ing netCDF dependent plugins, it cannot find netcdf, hdf5, libz.  I assume it should be using VisIt's libraries, to avoid conflicts.

How do I set the environment variables properly for cmake/make to find the proper libraries and headers?

If you tested this recently, for which Linux OS and VisIt versions was it successful?

Thanks,
Lisa

**Comment by josephzhang8** [comment]
@qshu 
@ejwalt@wm.edu
Hi Eric, Jon: can u plz help? Thx.

**Comment by qiangshu** [comment]
Did you try adding VisIt library path to $LIBRARY_PATH?

**Comment by josephzhang8** [comment]
Hi Jon:

I haven't done anything yet. Could you please make those changes? Thx.

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by qiangshu** [comment]
Joseph,
   I mean Lisa can try to add VisIt lib path into her system environment variable  $LIBRARY_PATH, since her building system can't find netcdf, hdf5 and zlib. VisIt has those libs.

**Comment by josephzhang8** [comment]
In case Lisa is not watching...

-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by lisalenorelowe** [comment]
Yes, I wrote the steps I tried here:
https://github.com/lisalenorelowe/schism_visit_plugin/blob/master/linux_build_instructions.md

Including setting the library path, since the plugin should really be using VisIt's libraries.

Eric Walter sent me some instructions on hacking the Makefile, I didn't try it yet.  I will let you know how it goes.

I guess I can try "LIBRARY_PATH" instead of just "LD_LIBRARY_PATH", but I suspect it won't matter.  We'll see.

Thanks for responding!

**Comment by lisalenorelowe** [comment]
Okay!  I found that if I hack those makefiles, I can compile the plugins.  (In that case, it is important *not* to set the paths.). Although it would be good if that wasn't necessary, we can go with that.

Do you have some example files in a public place that I can use to test whether it works in VisIt?

That way other people can try it as well.  (Also, that way I don't have to dig one up, or figure out that it does or doesn't work with OLD or NOT_OLD outputs, etc.)

@josephzhang8 
@qshu
@ejwalt@wm.edu
@zliu@disl.org

**Comment by josephzhang8** [comment]
I've added info on sample outputs (from OLDIO or scribe)  in the manual:

https://schism-dev.github.io/schism/master/getting-started/visualization.html


-Joseph

Y. Joseph Zhang
Web: schism.wiki
Office: 804 684 7466

**Comment by lisalenorelowe** [comment]
O-KAY!  Hooray!
https://github.com/lisalenorelowe/schism_visit_plugin/blob/master/OLD_IO.png

What do I do to get the New IO to do that?  Instead of:
https://github.com/lisalenorelowe/schism_visit_plugin/blob/master/NEW_IO.png

@josephzhang8
@qshu
@ejwalt@wm.edu
@zliu@disl.org

**Comment by josephzhang8** [comment]
You should use same plugin option 'SCHISM' for both old and new formats. It seems the plugins are not working properly under new.
Note that under new I/O, visIT will need out2d*.nc zCoordinates*.nc for any 3D variables so make sure those files are in the same directory.


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/

**Comment by lisalenorelowe** [comment]
Okay, for the old plugin, it knew it was SCHISM without me telling it explicitly.

The new plugin (almost) works, I just have to choose "SCHISM" when I open the file.

It 'almost' works because there is a weird artifact...that grey dashed vertical line.  To get depth to show in VisIt, you have to scale Z.  For that successful old_io image, I scaled Z by 100.  But if it has the artifact, then when I scale Z, I just get that vertical line taking over.  What is that line?  Is it in the output file?  Or something the plugin is doing?
https://github.com/lisalenorelowe/schism_visit_plugin/blob/master/artifact.png

@UMZhilongLiu
@josephzhang8

**Comment by josephzhang8** [comment]
It may be related to the different treatments of junk values btw the 2 formats in the plugins. If you see surface salinity correctly I think you are on the same page with us.

@Jon: I also found some very high 'elevation' with new plugin when visualizing 3D object. I simply set the y- or z-axis range in VisIT to get better view.

Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/

**Comment by lisalenorelowe** [comment]
I really need to be able to get rid of that artifact to do movies and transects.  Is it something folks are working on? 

@josephzhang8 
@jon
@UMZhilongLiu

**Comment by lisalenorelowe** [comment]
Hi Joseph, I am able to eliminate the 'artifacts' by using Threshold:Variable:Show zone if "all in range".  Everything is working great, thanks!

@josephzhang8
@UMZhilongLiu

<img width="317" alt="AllInRange" src="https://user-images.githubusercontent.com/22916939/232867120-442bba83-1293-4076-b220-927c4d350f32.png">

**Comment by josephzhang8** [comment]
That's good to know; thx Lisa. I'm in CA and meeting with DWR crowd now and will discuss this among others with them.


Regards,
-------------------------------
Joseph Zhang
(804)684 7595 (office)
SCHISM web: http://ccrm.vims.edu/schism/
