### ISSUE TITLE
Unable to find SCHISM type in VisIT/Windows

### ISSUE THREAD

**Issue by jamal919** [schism-dev/schism_visit_plugin#7]
Hello all, 

I typically use Linux, hence always compiled the VisIT plugin. Recently, for training purposes I needed to install VisIT under Windows using the precompiled .dll files, but unable to work with the SCHISM type netcdf files, as the extension does not appear in the extension list.

I have tried both 3.3.1 and 3.1.4, and in both cases I am facing the same problem - SCHISM file type is not installed. Although I have the prop and gr3 filetype in the extensions list. What could be the problem here - any idea?

Thanks.

**Comment by lisalenorelowe** [comment]
@jamal919  Did you post this to the main SCHISM mailing list?  I'm not sure how much traffic this (plugin) site gets.

**Comment by kjnam** [comment]
@jamal919 Sorry I have not followed this repository so far. Would you copy `netcdf_c++.dll` to `%userprofile%\LLNL\VisIt3.3.1` (or an equivalent place depending on the version) and try it again? The file does not go into the database directory.

**Comment by jamal919** [comment]
Hi @kjnam, @lisalenorelowe  - thanks for your reply. 

@kjnam 
> Did you mean netcdf_c++.dll? Is there a pre-compiled version of the dll exists somewhere? I could only find the installer for netCDF-C. For C++, I can only find the corresponding sourcecode. May be I have missed it.

This is what I was going to post, while doing a file-find running, and I saw netcdf_c++.dll inside the installation of 2.13.3, and copying it to corresponding folder of 3.3.1 indeed worked!

**Comment by kjnam** [comment]
@jamal919 Sorry about the typo, and glad that it worked.
